// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketBoard.Api.Data;

#nullable disable

namespace TicketBoard.Api.Migrations
{
    [DbContext(typeof(TicketDbContext))]
    [Migration("20260803100500_SeedMoreData")]
    partial class SeedMoreData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketBoard.Api.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Payment",
                            Priority = "High",
                            Title = "Payment Failed"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Authentication",
                            Priority = "Medium",
                            Title = "Unable to Login"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Technical",
                            Priority = "Low",
                            Title = "Page Not Loading"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Database",
                            Priority = "High",
                            Title = "Database Timeout"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Authentication",
                            Priority = "Medium",
                            Title = "Password Reset Link Expired"
                        },
                        new
                        {
                            Id = 6,
                            Category = "UI/UX",
                            Priority = "Low",
                            Title = "UI Alignment Issue on Mobile"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Payment",
                            Priority = "High",
                            Title = "Server Error 500 on Checkout"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Content",
                            Priority = "Low",
                            Title = "Missing Localization Strings"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
